### ISSUE TITLE
Question: how to set the shortcut folder

### ISSUE THREAD

**Issue by grandtiger** [atom/grunt-electron-installer#100]
I managed to create an installer with this tool. However, the shortcut of my app is put under "GitHub, Inc", and I couldn't figure out how to change it to something else. Could anyone help me with this? Thanks a lot!

**Comment by kumarharsh** [comment]
+1, and my shortcut name is "Electron.exe" for some reason, when everywhere in my app, I've named it MYAPP

**Comment by stephanec1** [comment]
+1, same as @kumarharsh, my shortcut name is "Electron.exe" and as @grandtiger  it is under "GitHub, Inc" folder.

**Comment by stephanec1** [comment]
Find a beginning of solution in this issue,

"The Desktop shortcut info will be based on the EXE's File Properties (i.e. right click on file => Properties), electron-packager lets you change this (or a bunch of other Electron tooling things)"

https://github.com/atom/grunt-electron-installer/issues/87

**Comment by stephanec1** [comment]
This is the solution use the version-string parameter of electron packager and this will solve this issue
