### ISSUE TITLE
Update.exe does not have an icon

### ISSUE THREAD

**Issue by MarshallOfSound** [atom/grunt-electron-installer#103]
Not sure what the expected behaviour is here, it's either

* Update.exe takes the icon of the main application
* Update.exe has it's own generic squirrel icon

But having an application with no icon looks quite bad (even for the few seconds it is visible for).  Is it possible to use https://github.com/atom/node-rcedit to set the icon much like `electron-packager` does

**Comment by paulcbetts** [comment]
Set the setupIcon property

**Comment by MarshallOfSound** [comment]
Sorry I don't think I communicated this clearly.  My `setupIcon` is set correctly as seen here.

![setup](https://cloud.githubusercontent.com/assets/6634592/13245893/662b0ef8-da64-11e5-9ab3-838e5ce1c35e.PNG)

But when installing for the briefest of moments, `Update.exe` appears in the task bar (maybe for like 2 - 3 seconds) without an icon.

![update](https://cloud.githubusercontent.com/assets/6634592/13245911/7c7f17da-da64-11e5-8c60-fd272e62fdfe.PNG)

**Comment by stephanec1** [comment]
Same issue for me

**Comment by paulcbetts** [comment]
Oh yes - file a bug on squirrel/squirrel.windows. Also, where can I get this Google Play app?!?!

**Comment by MarshallOfSound** [comment]
@paulcbetts Will do thanks.

The player used to be WinForms based but the electron one is in a `3.0.0` branch here.  
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/tree/dev/3.0.0
