### ISSUE TITLE
Can't install Windows

### ISSUE THREAD

**Issue by caseymorrisus** [atom/grunt-electron-installer#23]
Tried to install using `npm install --save-dev grunt-electron-installer`
Windows 7.   

    npm WARN package.json my-project-name@0.1.0 No description
    npm WARN package.json my-project-name@0.1.0 No repository field.
    npm WARN package.json my-project-name@0.1.0 No README data
    npm http GET https://registry.npmjs.org/grunt-electron-installer
    npm http 304 https://registry.npmjs.org/grunt-electron-installer
    npm http GET https://registry.npmjs.org/grunt-electron-installer/-/grunt-electron-installe
    r-0.31.0.tgz
    npm http 200 https://registry.npmjs.org/grunt-electron-installer/-/grunt-electron-installe
    r-0.31.0.tgz
    npm ERR! Error: ENOENT, lstat 'C:\Users\Casey\AppData\Local\Temp\npm-30232-                _bKAllyD\143019
    5649360-0.18368915328755975\package\vendor\Setup.exe'
    npm ERR! If you need help, you may report this *entire* log,
    npm ERR! including the npm and node versions, at:
    npm ERR!     <http://github.com/isaacs/npm/issues>
    
    npm ERR! System Windows_NT 6.1.7601
    npm ERR! command "E:\\Programs\\nodejs\\\\node.exe" "E:\\Programs\\nodejs\\node_modules\\n
    pm\\bin\\npm-cli.js" "i" "-S" "grunt-electron-installer" "--msvs_version=2013"
    npm ERR! cwd C:\Users\Casey\Electron Apps
    npm ERR! node -v v0.10.24
    npm ERR! npm -v 1.3.21
    npm ERR! path C:\Users\Casey\AppData\Local\Temp\npm-30232-_bKAllyD\1430195649360-        0.1836891
    5328755975\package\vendor\Setup.exe
    npm ERR! fstream_path C:\Users\Casey\AppData\Local\Temp\npm-30232-    _bKAllyD\1430195649360-0
    .18368915328755975\package\vendor\Setup.exe
    npm ERR! fstream_type File
    npm ERR! fstream_class FileWriter
    npm ERR! code ENOENT
    npm ERR! errno 34
    npm ERR! fstream_stack            E:\Programs\nodejs\node_modules\npm\node_modules\fstream\lib\writer
    .js:284:26
    npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
    npm ERR!
    npm ERR! Additional logging details can be found in:
    npm ERR!     C:\Users\Casey\Electron Apps\npm-debug.log
    npm ERR! not ok code 0

**Comment by cscsomers** [comment]
I used this article and got it working, hope it helps.
https://www.robertkehoe.com/2015/03/fix-node-gyp-rebuild-error-on-windows/

**Comment by caseymorrisus** [comment]
Unfortunately the original issue is solved, but I now run into an untar error. Running `npm cache clean` does not fix the issue.

    npm ERR! tar.unpack untar error C:\Users\Casey\AppData\Roaming\npm-cache\grunt-electron-in
    staller\0.33.0\package.tgz
    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "E:\\Programs\\nodejs\\\\node.exe" "E:\\Programs\\nodejs\\node_modules\\npm\
    \bin\\npm-cli.js" "install" "--save-dev" "grunt-electron-installer"
    npm ERR! node v0.12.2
    npm ERR! npm  v2.7.4
    npm ERR! path C:\Users\Casey\ImageMinifier\node_modules\grunt-electron-installer\vendor\Se
    tup.exe
    npm ERR! code ENOENT
    npm ERR! errno -4058

    npm ERR! enoent ENOENT, lstat 'C:\Users\Casey\ImageMinifier\node_modules\grunt-electron-in
    staller\vendor\Setup.exe'
    npm ERR! enoent This is most likely not a problem with npm itself
    npm ERR! enoent and is related to npm not being able to find a file.
    npm ERR! enoent

**Comment by kevinsawicki** [comment]
```
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
```

This is a really outdated version of npm, would it be possible for you to upgrade to a newer version?

**Comment by kevinsawicki** [comment]
Nevermind, it looks like you did in your subsequent comment

```
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
```

This seems like an npm error since it is failing to unpack the library for some reason, I'd recommend reporting it against https://github.com/npm/npm/issues with the details of the log you are seeing.

Going to close this out here since it seems like it is outside of what this library controls since it is failing with `untar error`.
