### ISSUE TITLE
Nothing happens running installer exe when app is already installed

### ISSUE THREAD

**Issue by bostondv** [atom/grunt-electron-installer#29]
When the app is already installed and the user tries to run the installer again, nothing happens. This has been confusing for a few of the testers in our app.

Could the installer display a dialog to let them know it's already installed or even just launch the app? 

Or is it possible to handle this ourselves within the squirrel events handles?

**Comment by paulcbetts** [comment]
@bostondv This is a bug in Squirrel I'm going to fix at some point, track it here: https://github.com/Squirrel/Squirrel.Windows/issues/317
