### ISSUE TITLE
How to check for updates?

### ISSUE THREAD

**Issue by sergiovilar** [atom/grunt-electron-installer#36]
I noticed that Squirrel Windows has an [API to ask for updates](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/api.md#methods-for-managing-updates), using grunt-electron-installer there's a way to check for updates? Case not, with which frequency Squirrel will ask for updates?

Thank you!

**Comment by sergiovilar** [comment]
Closing here, please see #37

**Comment by jessep** [comment]
Is there a reason not to merge the #37? Seems pretty critical.

**Comment by sergiovilar** [comment]
@jessep the last commit here was in may, no hope to someone answer anything here. Read the [Atom Auto update](https://github.com/atom/atom/tree/master/src/browser) source and you'll be fine.

Please let me know if you need something.

**Comment by jessep** [comment]
Thanks @sergiovilar :)

**Comment by havenchyk** [comment]
@sergiovilar sorry, if it's not the best place to ask, but could you please describe, how you make auto updates with this package? Do you use windows to create windows installers?

**Comment by sergiovilar** [comment]
@havenchyk I had to read the Atom auto update source, as I described above and, yes, you'll need a windows machine with visualstudio to get this package working. I recommend using a CI like Appveyor.

**Comment by paulcbetts** [comment]
> @jessep the last commit here was in may, no hope to someone answer anything here.

Incorrect!

**Comment by sergiovilar** [comment]
Look who is here after six months!!
