### ISSUE TITLE
squirrel.exe and Update.exe, which one can be depended on by my app?

### ISSUE THREAD

**Issue by duanyao** [atom/grunt-electron-installer#42]
After installation, there are 2 files -- `<installation_dir>\Update.exe` and `<installation_dir>\app-x.y.z\squirrel.exe` -- installed, and seems the same.

Why both of them exist? which one can be executed by my app (I want to use it to create shortcuts)? Are they guaranteed to exist in future versions of grunt-electron-installer?

**Comment by paulcbetts** [comment]
Update.exe is the version that is actually used to update and install your app and the one you should rely on. Squirrel.exe is the latest version of Update.exe - during update, `<installation_dir>\Update.exe` will look for that Squirrel.exe and use it to update itself (i.e. so your users don't get stuck on an old version of Squirrel).

**Comment by duanyao** [comment]
I see, thank you very much！
