### ISSUE TITLE
File not found: `LICENSE`

### ISSUE THREAD

**Issue by teleclimber** [atom/grunt-electron-installer#49]
I get this when I try to run this Grunt task:

```
Running "create-windows-installer:x64" (create-windows-installer) task
>> File not found: 'LICENSE'.
Warning: Command failed: C:\Users\ollie\_TEMP\cc_build\gruntit\node_modules\grun
t-electron-installer\vendor\nuget.exe pack C:\Users\ollie\AppData\Local\Temp\squ
irrel-installer-115717-9376-72k146\CC-editor2.nuspec -BasePath C:\Users\ollie\_T
EMP\cc_build\electron\out\R -OutputDirectory C:\Users\ollie\AppData\Local\Temp\s
quirrel-installer-115717-9376-72k146 -NoDefaultExcludes
File not found: 'LICENSE'.
 Use --force to continue.

Aborted due to warnings.
```

I tried `grunt --force` but that didn't seem to help. The task just ended and did not produce an installer.

I made sure I had a "license" field in my app's package.json, and I even added files `LICENSE`, `LICENSE.md`, `LICENSE.txt` in the same directory as my app's package.json. None of these things have allowed to me to get past this error.

What am I missing? Thanks.

**Comment by paulcbetts** [comment]
LICENSE needs to be in the same folder as electron.exe (i.e. `C:\Users\ollie\_T
EMP\cc_build\electron\out\R`)
