### ISSUE TITLE
Error: Unable to read resources\app\package.json

### ISSUE THREAD

**Issue by eightytwo** [atom/grunt-electron-installer#50]
When I run `grunt create-windows-installer` I receive the following error:

`Running "create-windows-installer:x64" (create-windows-installer) task
Warning: Unable to read "F:\app\build\my-app-64\resources\app\package.json" file (Error code: ENOENT). Use --force to continue.`

Here is my Gruntfile.js...
```
module.exports = function(grunt) {
  grunt.loadNpmTasks('grunt-contrib-clean');
  grunt.loadNpmTasks('grunt-electron-installer');

  grunt.initConfig({
    'create-windows-installer': {
      x64: {
        appDirectory: 'build/my-app-64',
        outputDirectory: 'build/installer64',
        authors: 'My Company',
        exe: 'myapp.exe'
      },
      ia32: {
        appDirectory: 'build/my-app-32',
        outputDirectory: 'build/installer32',
        authors: 'My Company',
        exe: 'myapp.exe'
      }
    },
    'clean': [ "build" ]
  });
}
```

I'm a little confused as to why this this task is trying to find `package.json` in `resources\app`? I don't actually have a resources directory. My `package.json` file sits beside my `Gruntfile.js` in `F:\app`.

Thanks for any help :)

**Comment by codegaze** [comment]
When you execute ```electron .``` in your terminal to test/run your app electron creates a ``dist`` folder in your ``electron_prebuild\resources\appnamefolder`` folder with your app folder inside. That's the appDirectory.

**Example:**
Your app folder: ```C:\my-app```
appDirectory: ```C:\\my-app\\node_modules\\electron-prebuild\\dist\\``` (task appends prebuild\dist\resources)
Folder with your app electron created: ```C:\\my-app\\node_modules\\electron-prebuild\\dist\\resources\\my-app``` (you need to rename this folder to app)

At least that's what worked for me

**Comment by codegaze** [comment]
What you need is to understand how your app works. Your app works through electron. Your executable will be electron.exe (or whatever name you give to electron.exe)

First thing you need to do after you 've finished with your app is  copy your app folder (only the files you need to make it work) in the dist directory of your electron installation folder.

**Example:**
Your app folder: ```C:\my-app```
Electron folder: ```C:\my-app\node_modules\electron-prebuild```
appDirectory: ```C:\\my-app\\node_modules\\electron-prebuild\\dist\\``` (task appends resources)
Folder you need to copy your app: ```C:\\my-app\\node_modules\\electron-prebuild\\dist\\resources\\``` (be sure to rename your folder to ```app``` )

**Remember:** The myapp.exe you have in your task is the name of the electron.exe inside your ```C:\\my-app\\node_modules\\electron-prebuild\\dist\\``` folder (This might save you a lot of time. It took me a some time to understand that thing...)

At least that's what worked for me.

**Comment by paulcbetts** [comment]
`appDirectory` is the compiled result of your app (i.e. the folder with electron.exe in it), not your source code
