### ISSUE TITLE
update Squirrel.Windows and publish

### ISSUE THREAD

**Issue by coderhaoxin** [atom/grunt-electron-installer#51]
due to https://github.com/Squirrel/Squirrel.Windows/issues/204

**Comment by coderhaoxin** [comment]
ping @paulcbetts

**Comment by paulcbetts** [comment]
This was fixed long ago, the current version of Squirrel.Windows is 0.99.3

**Comment by coderhaoxin** [comment]
But the commit message shows

```
rcedit.exe   Update to Squirrel.Windows 0.8.0 (Squirrel/Squirrel.Windows@9a06fb7)   7 months ago
```

**Comment by paulcbetts** [comment]
rcedit doesn't change that often

**Comment by thughes** [comment]
@coderhaoxin If you are having issues running `rcedit.exe` make sure you have the Microsoft Visual C++ 2010 Redistributable Package installed:
http://www.microsoft.com/en-us/download/details.aspx?id=13523
https://chocolatey.org/packages/vcredist2010

**Comment by coderhaoxin** [comment]
@thughes thanks, it works :+1:
