### ISSUE TITLE
is there a way about electron call  another program？

### ISSUE THREAD

**Issue by huangxok** [atom/grunt-electron-installer#55]
I met a problem.
I used a section of code call another web program interface,it works normally in web browser.
In client, it has no effect,it doesn't work.
Is there one or more way that could call the browser or other program?

**Comment by paulcbetts** [comment]
Think you've got the wrong repo!

**Comment by huangxok** [comment]
ok! maybe I dont describe clearly! I inserted a section of code in the page,it just a javascript code
like this：
<script charset="utf-8" type="text/javascript" src="http://wpa.b.qq.com/cgi/wpa.php?key=XzkzODA1ODQ1OV81OTMxMF80MDA4OTg1MTY2Xw"></script>
this code‘s function is call a tencent’s client named QQ which is one chatting tools,if the OS install QQ
and could use the client(QQ) to communication(I want to use the chat tools complete the Online customer function).
this code could work on web browser,but it doesn't work on electron-installer client.
so I want to learn about electron-installer  whether if call the interface or other program!.

thanks again!
