### ISSUE TITLE
Generated version it's not correct

### ISSUE THREAD

**Issue by paul321** [atom/grunt-electron-installer#64]
I have an app that it's on version 0.1.112 all was fine until i updated to latest version, the instaler generated App-0.1.112-full.nupkg (older version) for newest version is generating App-0.1112-full.nupkg and this is because of this line

metadata.version = metadata.version.replace(/\.(\d+)$/, '$1');

**Comment by maxbrunsfeld** [comment]
Hey, sorry about that @paul321. I think this is fixed in v1.0.4. Thanks for the report.
