### ISSUE TITLE
about SyncReleases

### ISSUE THREAD

**Issue by zh99998** [atom/grunt-electron-installer#70]
I use remoteReleases in grunt config but nothing happens.

then i try call SyncReleases.exe directly

```bash
C:\Users\11399\Documents\GitHub\maotama\node_modules\grunt-electron-installer\vendor\SyncReleases.exe -u https://github.com/mycard/maotama-win32 -r C:\Users\11399\Documents\GitHub\maotama\release
```

and then i only got a **empty** RELEASE file.

the repo: https://github.com/mycard/maotama-win32

**Comment by paulcbetts** [comment]
@zh99998 SyncReleases only works against a remote URL directly serving a release directory, or a GitHub repo using the Releases feature. If you're using the direct serving, you also need to upload your RELEASES file
