### ISSUE TITLE
When pinning the app on Windows 8/10 it creates a new icon and it won't work properly.

### ISSUE THREAD

**Issue by lipis** [atom/grunt-electron-installer#72]
The installer works perfectly, but when we try to pin the app in the taskbar it creates a new icon and it is not exactly the right behaviour. Is there anything we can do about this?

**Comment by paulcbetts** [comment]
Call `app.setAppUserModelId('com.squirrel.YOURNUGETPKGID.YOUREXENAMEWITHOUTDOTEXE')` in your browser process. For example:

```
app.setAppUserModelId('com.squirrel.slack.slack')  // Package name is 'slack', executable is 'slack.exe'
```

**Comment by lipis** [comment]
Thanks! :dancer: 

Maybe we should add the `app.setAppUserModelId` in the docs?
https://github.com/atom/electron/blob/master/docs/api/app.md

**Comment by paulcbetts** [comment]
What we _should_ do is auto-detect if you're using Squirrel and just Do It For You™

**Comment by lipis** [comment]
Some apps want to run in multiple instances though.. so I'm not sure if it _should_ be default.. :)
