### ISSUE TITLE
Nuget.exe "Invalid URI: The format of the URI could not be determined."

### ISSUE THREAD

**Issue by Janneman84** [atom/grunt-electron-installer#74]
I'm trying to build a Windows installer in W10 but it keeps breaking when nuget.exe is called. The paths shown are correct. The .nuspect file is present and its xml content looks fine.

I tried updating nuget.exe to the latest version and using admin rights, but no luck.

I have not idea what the problem is, any suggestions?

**Comment by paulcbetts** [comment]
Can you paste in your nuspec file or the parameters you're giving to grunt-electron-installer?

**Comment by Janneman84** [comment]
```xml
<?xml version="1.0" encoding="utf-8"?><package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd"> <metadata> <id>AgeReader</id> <title>AgeReader</title> <version>0.1.1</version> <authors>Diagnoptics</authors> <owners>Diagnoptics</owners> <iconUrl>./assets/images/diagnoptics.ico</iconUrl> <requireLicenseAcceptance>false</requireLicenseAcceptance> <description>descriptie</description> </metadata> <files> <file src="locales\**" target="lib\net45\locales" /> <file src="resources\**" target="lib\net45\resources" /> <file src="*.bin" target="lib\net45" /> <file src="*.dll" target="lib\net45" /> <file src="*.pak" target="lib\net45" /> <file src="icudtl.dat" target="lib\net45\icudtl.dat" /> <file src="LICENSE" target="lib\net45\LICENSE" /> <file src="AgeReader.exe" target="lib\net45\AgeReader.exe" /> </files></package>
```

[16:55:08] Error: Command failed: C:\Diagnoptics\node_modules\electron-windows-installer\vendor\nuget.exe pack C:\Users\janne\AppData\Local\Temp\squirrel-installer-115103-3252-1eos5vy\AgeReader.nuspec -BasePath C:\Diagnoptics\release\v0.33.8\win32-ia32 -OutputDirectory C:\Users\janne\AppData\Local\Temp\squirrel-installer-115103-3252-1eos5vy -NoDefaultExcludes

I'm using electron-windows-installer for gulp by the way.

**Comment by paulcbetts** [comment]
@Janneman84 Your IconURL isn't a URL, it's a path. Make it a URL.

**Comment by Janneman84** [comment]
Thank you this worked, I must have overlooked this. I didn't realize entering a path would be a problem.
