### ISSUE TITLE
[Win32] Is it possible to make the app auto start on login?

### ISSUE THREAD

**Issue by lipis** [atom/grunt-electron-installer#75]

**Comment by paulcbetts** [comment]
This is an example of a thing you'd do in a Squirrel hook - on install / update, you'd set the regkey in JavaScript in your app

**Comment by lipis** [comment]
So my next question would be.. what exactly I should write there there in order to achieve that goal? (and still be able to autoupdate through that version and all)

**Comment by paulcbetts** [comment]
https://github.com/atom/atom/blob/master/src/browser/squirrel-update.coffee is a good example

**Comment by lipis** [comment]
@paulcbetts Thanks!
