### ISSUE TITLE
Add an option to not create MSI installer.

### ISSUE THREAD

**Issue by lipis** [atom/grunt-electron-installer#79]
There is `--no-msi` option in `Update.exe` and if it's already working it would be nice to add it to the [`README.md`](https://github.com/atom/grunt-electron-installer/blob/master/README.md).

**Comment by hankbao** [comment]
+1

**Comment by antoinepairet** [comment]
Since #82 was merged, this can be closed :-)

**Comment by hankbao** [comment]
Great, thanks.
