### ISSUE TITLE
Squirrel not found

### ISSUE THREAD

**Issue by leonardoxh** [atom/grunt-electron-installer#81]
Hi,

I'm developing a windows application with electron, everything works fine but when I try update the app with the electron auto-updater module I receive a error "Squirrel not found".

What i'm missing?

Is possible use electron auto-updater module with this package?

**Comment by leonardoxh** [comment]
I made a mistake when try upgrade to a new version.

With the installed version works really good.

**Comment by soukiii** [comment]
I am having the same problem. How exactly did you resolved it?
