### ISSUE TITLE
Question: is it recommended way to build installer?

### ISSUE THREAD

**Issue by havenchyk** [atom/grunt-electron-installer#88]
Hi, I'm still wondering, if grunt-electron-installer the recommended way to build installer?

**Comment by kevinsawicki** [comment]
It is a supported way, and I would recommend it if you are okay using grunt and like the configuration options it provided.

There is also https://www.npmjs.com/package/electron-installer-squirrel-windows which I've never used but looks to be a command line option that doesn't require grunt.

**Comment by paulcbetts** [comment]
grunt-electron-installer is the current supported way to create Electron Squirrel.Windows installers, it's what Slack and Atom both use, and it's the project that I update every release of Squirrel.Windows.

**Comment by havenchyk** [comment]
@kevinsawicki  @paulcbetts that's great, but there is also [electron-builder](https://github.com/loopline-systems/electron-builder) which many developers use. I'm ok with grunt and I would like to set up updates with squirrel as well, but it's not clear for me, is there any difference in build process between grunt-electron-installer and electron-builder. Also electron-builder allows to make builds for Mac.

I ask this question because I can't find in docs the "recommended" or "official" way. 

Thanks for your answers and all your work!

**Comment by paulcbetts** [comment]
Yes, electron-builder uses NSIS, a completely different installation technology

**Comment by havenchyk** [comment]
@paulcbetts so, is it correct, that grunt-electron-installer creates exactly installers to use it with squirrel and not "interactive" installer like msi that provided by electron-builder?

**Comment by paulcbetts** [comment]
@havenchyk grunt-electron-installer will create a Setup.exe that you can give to users - if you want to see the experience of what a Squirrel-based installer does, install Atom or Open Live Writer

**Comment by havenchyk** [comment]
@kevinsawicki sorry for all the noise, but are you recommend to make a build on the same OS as a target? E.g. on windows for windows or it's not necessary?

**Comment by kevinsawicki** [comment]
> on windows for windows or it's not necessary?

It should be possible to build Windows installers on Mac/Linux when mono and wine are installed. @paulcbetts would know more about it since he added support for that to squirrel.

Support for it was added to this plugin in #80

**Comment by fasterthanlime** [comment]
AFAIK:

  * MSI generation isn't supported on non-Windows platforms
  * The `Setup.exe` produced on Linux with wine+mono is a noop because the wrong `Update.exe` is packed into the installer, cf. ongoing discussion on #80 

Hoping to fix the latter soon though!

**Comment by havenchyk** [comment]
@paulcbetts could you please shed the light on this comment?

> It should be possible to build Windows installers on Mac/Linux when mono and wine are installed. @paulcbetts would know more about it since he added support for that to squirrel.
Support for it was added to this plugin in #80

**Comment by paulcbetts** [comment]
Support is there but it's got some bugs, we need to fix them up, @fasterthanlime has done some great work looking into it, but some of the caveats (No deltas, no MSI files) are a real drag.

**Comment by paulcbetts** [comment]
If y'all didn't know about it, AppVeyor is a great way to make Windows builds without having to deal with setting up Windows yourself, it's like a Windows version of Travis CI

**Comment by havenchyk** [comment]
@paulcbetts I just would like to find the way to make installers for mac and for windows with working auto-updating. Maybe anyone can share an example of sample where it's working. It would really great

**Comment by havenchyk** [comment]
So, electron-builder is a proper solution. After latest changes and merging with electron-complete-builder, it uses electron-winstaller under the hood (temp fork for now, but will be replaced soon).

I'd recommend to use electron-builder.
