### ISSUE TITLE
Warning: You must install both Mono and Wine on non-Windows Use --force to continue.

### ISSUE THREAD

**Issue by btelintelo** [atom/grunt-electron-installer#94]
When I run the simple grunt script defined on the help page:
Running "create-windows-installer:x64" (create-windows-installer) task
Warning: You must install both Mono and Wine on non-Windows Use --force to continue.

I have wine version 1.6.1_1 installed which also has mono.  I also have winetricks installed as well.

**Comment by tylerITP** [comment]
Are you on a Mac? All I had to do was brew install mono

**Comment by btelintelo** [comment]
DOH!  I was following how to install mono on the wine page!  Now it all works!  Thank you!
